"use client";

import { FormEvent, useEffect, useState } from "react";
// THÊM: Import BookOpen
import { Edit3, Plus, Search, Trash2, Users, BookOpen } from "lucide-react"; 
import { userApi } from "@/services/userApi";
// THÊM: Import Modal
import UserEnrollmentModal from "@/components/admin/UserEnrollmentModal"; 

type User = { taiKhoan: string; hoTen: string; email: string; soDt?: string; maLoaiNguoiDung?: string };
const list = (value: unknown): User[] => Array.isArray(value) ? value as User[] : (((value as { items?: User[] })?.items || []) as User[]);

export default function AdminUsersPage() {
    const [users, setUsers] = useState<User[]>([]); const [types, setTypes] = useState<{ maLoaiNguoiDung: string; tenLoaiNguoiDung: string }[]>([]); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [keyword, setKeyword] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<User | null>(null); const [form, setForm] = useState({ taiKhoan: "", matKhau: "", hoTen: "", email: "", soDt: "", maLoaiNguoiDung: "HV" });
    
    // THÊM: State cho Modal Ghi danh
    const [enrollModalOpen, setEnrollModalOpen] = useState(false); 
    const [selectedUserForEnroll, setSelectedUserForEnroll] = useState<string | null>(null);

    const load = async () => { const [result, typeResult] = await Promise.all([userApi.getUsersPagination(page, 8), userApi.getUserTypes()]); const data = result.data as unknown; setUsers(list(data)); setTotalPages(Math.max(1, Number((data as { totalPages?: number })?.totalPages || 1))); setTypes((Array.isArray(typeResult.data) ? typeResult.data : []) as { maLoaiNguoiDung: string; tenLoaiNguoiDung: string }[]); };
    useEffect(() => { load(); }, [page]);
    const visible = users.filter((user) => `${user.taiKhoan} ${user.hoTen} ${user.email}`.toLowerCase().includes(keyword.toLowerCase()));
    
    const showForm = (user?: User) => { setEditing(user || null); setForm({ taiKhoan: user?.taiKhoan || "", matKhau: "", hoTen: user?.hoTen || "", email: user?.email || "", soDt: user?.soDt || "", maLoaiNguoiDung: user?.maLoaiNguoiDung || "HV" }); setOpen(true); };
    
    // THÊM: Hàm mở Modal ghi danh
    const openEnrollModal = (taiKhoan: string) => { setSelectedUserForEnroll(taiKhoan); setEnrollModalOpen(true); };

    const submit = async (event: FormEvent) => { event.preventDefault(); const payload = form.matKhau ? form : (({ matKhau: _password, ...withoutPassword }) => withoutPassword)(form); if (editing) await userApi.updateUser(payload); else await userApi.addUser(payload); setOpen(false); await load(); };
    const remove = async (user: User) => { if (window.confirm(`Xóa tài khoản "${user.taiKhoan}"?`)) { await userApi.deleteUser(user.taiKhoan); await load(); } };
    
    return <div><header className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#237c73]">Accounts</p><h1 className="mt-2 text-3xl font-black tracking-tight text-[#123b3a]">Quản lý người dùng</h1><p className="mt-2 text-sm text-slate-500">Phân quyền và cập nhật thông tin tài khoản.</p></div><button type="button" onClick={() => showForm()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#123b3a] px-4 py-3 text-sm font-bold text-white"><Plus className="h-4 w-4" />Thêm người dùng</button></header><section className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-[0_8px_30px_rgba(30,65,64,0.05)]"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><p className="text-sm font-bold text-[#123b3a]"><Users className="mr-2 inline h-4 w-4" />Danh sách tài khoản</p><label className="flex w-full items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 sm:w-72"><Search className="h-4 w-4 text-slate-400" /><input value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="Tìm người dùng" className="w-full bg-transparent text-sm outline-none" /></label></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#f7faf9] text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Tài khoản</th><th className="px-5 py-4">Họ tên</th><th className="px-5 py-4">Email</th><th className="px-5 py-4">Vai trò</th><th className="px-5 py-4 text-right">Thao tác</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map((user) => <tr key={user.taiKhoan} className="hover:bg-[#fbfdfc]"><td className="px-5 py-4 font-semibold text-[#123b3a]">{user.taiKhoan}</td><td className="px-5 py-4 text-slate-700">{user.hoTen}</td><td className="px-5 py-4 text-slate-500">{user.email}</td><td className="px-5 py-4"><span className="rounded-full bg-[#e6f4f1] px-2.5 py-1 text-xs font-bold text-[#237c73]">{user.maLoaiNguoiDung || "HV"}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2">
        {/* THÊM: Nút Ghi danh */}
        <button type="button" title="Quản lý ghi danh" onClick={() => openEnrollModal(user.taiKhoan)} className="rounded-lg p-2 text-slate-400 hover:bg-amber-50 hover:text-amber-600"><BookOpen className="h-4 w-4" /></button>
        <button type="button" title="Sửa người dùng" onClick={() => showForm(user)} className="rounded-lg p-2 text-slate-400 hover:bg-[#e6f4f1] hover:text-[#237c73]"><Edit3 className="h-4 w-4" /></button><button type="button" title="Xóa người dùng" onClick={() => remove(user)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-slate-100 px-5 py-4 text-sm"><span className="text-slate-500">Trang {page} / {totalPages}</span><div className="flex gap-2"><button type="button" disabled={page === 1} onClick={() => setPage(page - 1)} className="rounded-lg border border-slate-200 px-3 py-2 font-semibold disabled:opacity-40">Trước</button><button type="button" disabled={page >= totalPages} onClick={() => setPage(page + 1)} className="rounded-lg bg-[#123b3a] px-3 py-2 font-semibold text-white disabled:opacity-40">Sau</button></div></div></section>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/35 p-4"><form onSubmit={submit} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-black text-[#123b3a]">{editing ? "Cập nhật người dùng" : "Thêm người dùng"}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["taiKhoan", "Tài khoản"], ["matKhau", "Mật khẩu"], ["hoTen", "Họ tên"], ["email", "Email"], ["soDt", "Số điện thoại"]].map(([key, label]) => <label key={key} className="text-sm font-semibold text-slate-600">{label}<input required={key !== "soDt" && !(key === "matKhau" && !!editing)} type={key === "matKhau" ? "password" : key === "email" ? "email" : "text"} disabled={key === "taiKhoan" && !!editing} value={form[key as keyof typeof form]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none" /></label>)}<label className="text-sm font-semibold text-slate-600">Vai trò<select value={form.maLoaiNguoiDung} onChange={(e) => setForm({ ...form, maLoaiNguoiDung: e.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 outline-none">{types.length ? types.map((type) => <option key={type.maLoaiNguoiDung} value={type.maLoaiNguoiDung}>{type.tenLoaiNguoiDung}</option>) : <><option value="HV">Học viên</option><option value="GV">Giáo vụ</option></>}</select></label></div><div className="mt-5 flex gap-3"><button type="button" onClick={() => setOpen(false)} className="w-1/2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold text-slate-600">Hủy</button><button type="submit" className="w-1/2 rounded-xl bg-[#123b3a] px-4 py-3 text-sm font-bold text-white">Lưu</button></div></form></div>}
    {/* THÊM: Hiển thị Modal Ghi danh */}
    <UserEnrollmentModal isOpen={enrollModalOpen} onClose={() => setEnrollModalOpen(false)} taiKhoan={selectedUserForEnroll} />
    </div>;
}